export const substractionLayerActions = {
  CREATE_SUBSTRACTION_LAYER: 'CREATE_SUBSTRACTION_LAYER',
  UPDATE_DATA_TYPE_ID: 'UPDATE_DATA_TYPE_ID',
  UPDATE_LAYERS_1: 'UPDATE_LAYERS_1',
  UPDATE_LAYERS_2: 'UPDATE_LAYERS_2',
  UPDATE_LAYER_NAME: 'UPDATE_LAYER_NAME',
  UPDATE_LAYER_DESCRIPTION: 'UPDATE_LAYER_DESCRIPTION',
  CLEAR_NEW_LAYER_DATA: 'CLEAR_NEW_LAYER_DATA'
}
