// store/actions/toolbar.ts

export const toolbarActions = {
  SET_ACTIVE_CURSOR: 'SET_ACTIVE_CURSOR',

  // Для сообщений:
  ADD_MESSAGE: 'ADD_MESSAGE',
  UPDATE_MESSAGE_TEXT: 'UPDATE_MESSAGE_TEXT',
  DELETE_MESSAGE: 'DELETE_MESSAGE', // <-- Новый экшен (удалить сообщение)
  SET_MEASURE_DISTANCE: 'SET_MEASURE_DISTANCE',
  SET_MARKERS: 'SET_MARKERS',
  ADD_ACTIVE_TOOL: 'ADD_ACTIVE_TOOL', // <-- Новый экшен (выставить, какой инструмент включен на данный момент)
  SET_CURRENT_DELETE_POINT: 'SET_CURRENT_DELETE_POINT',
  SET_MESSAGE: 'SET_MESSAGE',
  CLEAR_ALL: 'CLEAR_ALL',
  ADD_LAYER_GEOM: 'ADD_LAYER_GEOM',
  ADD_GEOMS_FOR_LAYER: 'ADD_GEOMS_FOR_LAYER',
  SET_GEOM_NOT_SAVED: 'SET_GEOM_NOT_SAVED',
  SET_CURRENT_GEOMS_IDS: 'SET_CURRENT_GEOMS_IDS',
  SET_GEOMS_FOR_NOT_SAVED: 'SET_GEOMS_FOR_NOT_SAVED',
  SET_SAVE_ALL: 'SET_SAVE_ALL',
  SET_SELECTED_OBJECTS: 'SET_SELECTED_OBJECTS'

}
