// store/actions/toolbarDrawing.ts
export const toolbarDrawingActions = {
  ADD_FEATURE: 'ADD_FEATURE',
  REMOVE_FEATURE: 'REMOVE_FEATURE',
  ADD_FEATURE_LINE: 'ADD_FEATURE_LINE',
  ADD_FEATURE_POINT: 'ADD_FEATURE_POINT',
  CLEAR_ALL: 'CLEAR_ALL',
  UPDATE_FEATURE_POSITION: 'UPDATE_FEATURE_POSITION',
  SET_ALL_GEOMS: 'SET_ALL_GEOMS'
}
