export const treeItemActions = {
  SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
  SET_SELECTED_KEBAB: 'SET_SELECTED_KEBAB',
  SET_SELECTED_LEGEND: 'SET_SELECTED_LEGEND',
  CLEAR_SELECTION: 'CLEAR_SELECTION'
}
