version: '3.8'

services:
  flask-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-service
    ports:
      - "5015:5015"
    volumes:
      - ./app:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
