
services:
  backend:
    env_file: .env
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  database:
    extends:
      file: ./backend/docker-compose.yml
      service: database

  frontend:
    env_file: .env
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend

  redis:
    env_file: .env
    extends:
      file: ./backend/docker-compose.yml
      service: redis

  promtail:
    extends:
      file: ./backend/docker-compose.yml
      service: promtail

  postgres-exporter:
    extends:
      file: ./backend/docker-compose.yml
      service: postgres-exporter
volumes:
  venvs:
  postgres-database:
